# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

BRAINTREE_MERCHANT_ID: 'x3b8rqbzcqs8t2y3'
BRAINTREE_PUBLIC_KEY: 'rhhft6h52pdtypqk'
BRAINTREE_PRIVATE_KEY: '88a0bf906618f4b8b1e3b91591b845d6'
