# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb6371671614649a6f67aee67f3422f03da063a895a99fee337a37f77b24221a312e77a5f73e682f3957d2e0eee2590f080dd1737d4a1afee6fcfc9cb9f58c46

test:
  secret_key_base: bb7f07bd632652dd37b3a12a6735c4cdc90fb26527d739cb4284662df1309451a3da1f50ad490cbe41ee9a57ce0de381262080354fad421f78396044d32f4779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
